# -*- coding: utf-8 -*-
"""24_09_02_hello_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6Tw8i2nw_KvdCWCn_0lgYI8GU2UTaAg
"""

print("Brave")

